export function DPSType() {
  return <div className="details-page">
    <header className="page-heading"><div><p>DPS TYPE · GUIA DE ESCALONAMENTO</p><h1>DPS por tipo</h1><span>Regras separadas para Bleed, Elemental e Chaos.</span></div><strong>3 <small>arquétipos</small></strong></header>
    <section className="detail-section"><header><h2>Bleed · físico DoT</h2><span>referências locais do PoB</span></header><div className="defense-list"><p><span>Base</span><b>17,36M Bleed DPS · 5.385 vida</b></p><p><span>Obrigatório</span><b>100% bleed e hit chance/RT</b></p><p><span>Escalonamento</span><b>maior hit físico + Bleed/Physical DoT Multiplier</b></p><p><span>Variantes</span><b>Lacerate/Eviscerate ≠ Puncture/Snipe</b></p></div></section>
    <section className="detail-section"><header><h2>Elemental · hit e ailments</h2><span>fire, cold e lightning</span></header><div className="defense-list"><p><span>Hit</span><b>base/added elemental, attack/cast rate, crit ou não-crit</b></p><p><span>Mitigação</span><b>resistência, penetration, exposure e curse</b></p><p><span>Ailments</span><b>ignite = fire DoT; shock/chill/freeze dependem do hit</b></p><p><span>Regra</span><b>penetration/exposure não são multiplicadores de ailment</b></p></div></section>
    <section className="detail-section"><header><h2>Chaos · hit, poison ou chaos DoT</h2><span>linha independente de elemental</span></header><div className="defense-list"><p><span>Hit/DoT</span><b>chaos damage, Chaos DoT Multiplier ou poison</b></p><p><span>Mitigação</span><b>chaos resistance, curse e Wither; não elemental penetration</b></p><p><span>Poison</span><b>base física/chaos do hit + chance, stacks e uptime</b></p><p><span>Regra</span><b>separar hit, poison e non-ailment chaos DoT</b></p></div></section>
    <section className="detail-section"><header><h2>Auditoria crítica dos XML PoE Ninja</h2><span>amostras locais comparadas</span></header><div className="defense-list"><p><span>Bleed alto observado</span><b>35,79M com 2.585 vida: DPS não é viabilidade</b></p><p><span>Referência defensiva</span><b>18,68M Bleed, 4.196 vida, 89,76 block</b></p><p><span>Alertas encontrados</span><b>95% hit, resistências incompletas e caos negativo</b></p><p><span>Regra de benchmark</span><b>comparar DPS + vida + caps + hit + sustain</b></p><p><span>Tree samples</span><b>agrupar por skill/ascendência; não copiar Puncture para Lacerate</b></p></div></section>
    <section className="detail-section"><header><h2>Checklist universal de PoB</h2><span>métrica comparável</span></header><div className="defense-list"><p><span>Configuração</span><b>alvo, charges, buffs, debuffs e uptime real</b></p><p><span>Defesa</span><b>75% elemental, caos adequado, vida/ES e sustain</b></p><p><span>Benchmark</span><b>separar DPS de hit, ailment, DoT e clear</b></p></div></section>
  </div>
}
